baseURL = 'https://jasoncmitchell.com'
languageCode = 'en-us'
title = 'Jason C. Mitchell'
theme = ["hugo-embed-pdf-shortcode", "digitalgarden"]

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Articles'
  url = '/articles'
  weight = 2
[[menu.main]]
  name = 'Scripting and Automation Portfolio'
  url = '/portfolio'
  weight = 3
[[menu.main]]
  name = 'Brief Curriculum Vitae'
  url = 'https://drive.google.com/file/d/14Ihyw956NovkMWslJNZGWWF7hHJLoA3_/view?usp=share_link'
  weight = 4


[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/CompareTheo'
  weight = 1
[[menu.social]]
  name = 'LinkedIn'
  url = 'https://linkedin.com'
  weight = 2
[[menu.social]]
  name = 'Email'
  url = 'mailto:info@jasoncmitchell.com'
  weight = 3


# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true